# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzArmConnection'
    subscriptionId: '766ad712-f5e2-460a-a621-1f1014bf72bb'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'webserver'
    location: 'France Central'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/CaucheMehdi/cloudtesting/master/azuredeploy_storage.json'
    overrideParameters: '-projectName myArmPipeline'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployArmTemplate'
  displayName: 'Run first Arm Deployment Pipeline'
